INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('alex', 'alex.alves@gmail.com', '1234')
INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('kelvin', 'kelvin.max@gmail.com', '4321')
INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('roberto','roberto.fulano@gmail.com', '5678')
INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('juliano', 'juliano.alves@gmail.com', '8765')
INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('carlos', 'carlos.teteu@gmail.com', '1357')
INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('kaio', 'kaio.ferreira@gmail.com', '7531')
INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('lord', 'lord.jubileu@gmail.com', '8910')
INSERT INTO USERS(NAME, EMAIL, PASSWORD)VALUES('skinner','skinner.tucam@gmail.com', '0198')

--TABLE WALLET-TYPE
INSERT INTO WALLET_TYPE(NAME, STATUS)VALUES('CASA', 'ATIVO')
INSERT INTO WALLET_TYPE(NAME, STATUS)VALUES('MODAS FIT', 'ATIVO')
INSERT INTO WALLET_TYPE(NAME, STATUS)VALUES('PADARIA', 'ATIVO')